//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelResrvation.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelDBEntities1 : DbContext
    {
        public HotelDBEntities1()
            : base("name=HotelDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgentTbl> AgentTbls { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<BranchTbl> BranchTbls { get; set; }
        public virtual DbSet<CustomerTbl> CustomerTbls { get; set; }
        public virtual DbSet<FoodTbl> FoodTbls { get; set; }
        public virtual DbSet<HotelStatu> HotelStatus { get; set; }
        public virtual DbSet<InvoiceTbl> InvoiceTbls { get; set; }
        public virtual DbSet<ReservationTbl> ReservationTbls { get; set; }
        public virtual DbSet<RightInfo> RightInfoes { get; set; }
        public virtual DbSet<RoleANDRightTbl> RoleANDRightTbls { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<SeasonTbl> SeasonTbls { get; set; }
        public virtual DbSet<ServiceTbl> ServiceTbls { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TransactionTbl> TransactionTbls { get; set; }
        public virtual DbSet<UserInfo> UserInfos { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
