//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelResrvation.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTbl
    {
        public int TId { get; set; }
        public Nullable<int> RId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
    
        public virtual InvoiceTbl InvoiceTbl { get; set; }
        public virtual ReservationTbl ReservationTbl { get; set; }
    }
}
